name: PDCBridgeTest
main: me.danny.qlib.testing.TestPlugin
version: 1.0.0
author: Danny
description: Library for defining PersistentDataTypes from complex types
api-version: 1.18
commands:
  testpdcbridge:
    usage: /<command>
    description: Test command